# Generated by Django 3.2 on 2022-07-06 04:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.about', verbose_name='Hakkımızda')),
            ],
            options={
                'verbose_name': 'Hakkımızda Maddeler',
                'verbose_name_plural': 'Hakkımızda Maddeler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChangeJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='change-journey', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Değişim Yolculuğu',
                'verbose_name_plural': 'Değişim Yolculukları',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Müşteri İncelemesi',
                'verbose_name_plural': 'Müşteri İncelemeleri',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomePageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Anasayfa Giriş Bloku',
                'verbose_name_plural': 'Anasayfa Giriş Bloku',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Resim')),
            ],
            options={
                'verbose_name': 'Resim',
                'verbose_name_plural': 'Resimler',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Anahtar Kelime',
                'verbose_name_plural': 'Anahtar Kelimeler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KVKKPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about/banner', verbose_name='Banner Image')),
                ('meta_keywords', models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'KVKK Sayfası SEO',
                'verbose_name_plural': 'KVKK Sayfası SEO',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Obezite ve Metabolik Cerrahi',
                'verbose_name_plural': 'Obezite ve Metabolik Cerrahi',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tedavi Planı',
                'verbose_name_plural': 'Tedavi Planları',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.treatmentplan', verbose_name='Tedavi Planı')),
            ],
            options={
                'verbose_name': 'Tedavi Planı Maddeler',
                'verbose_name_plural': 'Tedavi Planı Maddeler',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomePageSeoSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.homepageseo')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.image')),
            ],
        ),
        migrations.AddField(
            model_name='homepageseo',
            name='meta_keywords',
            field=models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='homepageseo',
            name='slides',
            field=models.ManyToManyField(related_name='intro_slides', through='page.HomePageSeoSlides', to='page.Image'),
        ),
        migrations.CreateModel(
            name='AboutSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_slides', to='page.about')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutBottomSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_slides_bottom', to='page.about')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.image')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='slides',
            field=models.ManyToManyField(related_name='about_slides', through='page.AboutSlides', to='page.Image'),
        ),
        migrations.AddField(
            model_name='about',
            name='slides_bottom',
            field=models.ManyToManyField(related_name='about_slides_bottom', through='page.AboutBottomSlides', to='page.Image'),
        ),
        migrations.CreateModel(
            name='TreatmentPlanTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=25, verbose_name='Adı')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.treatmentplan')),
            ],
            options={
                'verbose_name': 'Tedavi Planı Translation',
                'db_table': 'page_treatmentplan_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TreatmentPlanItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('info', models.CharField(max_length=100, verbose_name='Madde')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.treatmentplanitem')),
            ],
            options={
                'verbose_name': 'Tedavi Planı Maddeler Translation',
                'db_table': 'page_treatmentplanitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SurgeryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, default='', max_length=80, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='surgery', verbose_name='Resim')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.surgery')),
            ],
            options={
                'verbose_name': 'Obezite ve Metabolik Cerrahi Translation',
                'db_table': 'page_surgery_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KVKKPageSeoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.kvkkpageseo')),
            ],
            options={
                'verbose_name': 'KVKK Sayfası SEO Translation',
                'db_table': 'page_kvkkpageseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KeywordsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.keywords')),
            ],
            options={
                'verbose_name': 'Anahtar Kelime Translation',
                'db_table': 'page_keywords_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomePageSeoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('title_intro', models.CharField(blank=True, default='', max_length=60, verbose_name='Başlık Girişi')),
                ('title', models.CharField(blank=True, default='', max_length=80, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('bottom_content', models.TextField(blank=True, default='', verbose_name='Alt Bant İçeriği')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.homepageseo')),
            ],
            options={
                'verbose_name': 'Anasayfa Giriş Bloku Translation',
                'db_table': 'page_homepageseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=150, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.faq')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru Translation',
                'db_table': 'page_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerReviewTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=80, verbose_name='Müşteri İsmi')),
                ('job_title', models.CharField(max_length=80, verbose_name='Meslek')),
                ('comment', models.CharField(max_length=250, verbose_name='Yorum')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.customerreview')),
            ],
            options={
                'verbose_name': 'Müşteri İncelemesi Translation',
                'db_table': 'page_customerreview_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Başlık')),
                ('intro', models.TextField(blank=True, default='', verbose_name='Giriş')),
                ('description_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Açıklama Girişi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.about')),
            ],
            options={
                'verbose_name': 'Hakkımızda Translation',
                'db_table': 'page_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutListTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('info', models.CharField(default='', max_length=100, verbose_name='Madde')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.aboutlist')),
            ],
            options={
                'verbose_name': 'Hakkımızda Maddeler Translation',
                'db_table': 'page_aboutlist_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
