# Generated by Django 3.2 on 2022-07-10 18:22

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20220710_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSeoSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.homepageseo')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='homepageseo',
            name='slides',
            field=models.ManyToManyField(related_name='intro_slides', through='page.HomePageSeoSlides', to='page.Image'),
        ),
        migrations.CreateModel(
            name='HomePageSeoSlidesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title_intro', models.CharField(blank=True, default='', max_length=60, verbose_name='Başlık Girişi')),
                ('title', models.CharField(blank=True, default='', max_length=80, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.homepageseoslides')),
            ],
            options={
                'verbose_name': 'home page seo slides Translation',
                'db_table': 'page_homepageseoslides_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
