# Generated by Django 3.2 on 2022-07-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20220710_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeJourney',
        )
    ]
